version: '3.1'

services:
  db:
    image: mysql
    container_name: database
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
    environment: 
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=imgrepo
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
    - "3306:3306"
    networks: 
      - img-repo-network

  backend:
    image: image-repo-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 1919
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./image-repo-backend/app
    restart: always
    ports: 
      - "1919:1919"
    networks:
      - img-repo-network

  frontend:
    image: image-repo-ui
    restart: always
    command: npm run serve
    container_name: frontend
    build:
      context: ./image-repo-ui/frontend
    ports:
    - "8080:8080"
    depends_on: 
      - "backend" 
    networks:
      - img-repo-network

networks:
  img-repo-network: